[profile.default]
solc_version = '0.8.19'
src = "src/contracts"
out = "out"
libs = ["lib"]

remappings = [
  "universal-rewards-distributor/=lib/universal-rewards-distributor",
  "openzeppelin/=lib/universal-rewards-distributor/lib/openzeppelin-contracts/contracts",
]
