[profile.default]
solc_version = '0.8.19'
evm_version = 'cancun'
src = "src/contracts"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./data" }]


remappings = [
  "universal-rewards-distributor/=lib/universal-rewards-distributor",
  "openzeppelin/=lib/universal-rewards-distributor/lib/openzeppelin-contracts/contracts",
]
